---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/josephjones/Desktop/gitFolder/thirdCpp/parameters'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: __ZN3Car5speedEi, symObjAddr: 0x0, symBinAddr: 0x100003F38, symSize: 0x18 }
  - { offsetInCU: 0x2CA3, offset: 0x2CA3, size: 0x8, addend: 0x0, symName: __ZN3Car5speedEi, symObjAddr: 0x0, symBinAddr: 0x100003F38, symSize: 0x18 }
  - { offsetInCU: 0x2CD6, offset: 0x2CD6, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x18, symBinAddr: 0x100003F50, symSize: 0x44 }
...
